# config/default.yaml
defaults:
  - _self_
  - train: default

qlora:
  r: 8
  alpha: 16
  dropout: 0.05
  quantization:
    load_in_4bit: True
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_compute_dtype: "float16"
    bnb_4bit_use_double_quant: True

paths:
  # Where to save the output of Phase 1
  distilled_checkpoint: "./checkpoints/distilled_student" 
  checkpoints: "./checkpoints"
  data_root: "./data/cosmos1050k"

dataset:
  modality: "CT" # Change to MRI or US for other runs
  split: "train"
  size: 512
  prompt_type: "box"

use_wandb: False